# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/ipc/msg_types/monitor_msg.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'src/ipc/msg_types/monitor_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#src/ipc/msg_types/monitor_msg.proto\x12\x11study_monitor.ipc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\nMonitorMsg\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x46\n\x14\x63oncentration_status\x18\x02 \x01(\x0b\x32&.study_monitor.ipc.ConcentrationStatusH\x00\x12)\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x18.study_monitor.ipc.ErrorH\x00\x42\t\n\x07payload\"I\n\x13\x43oncentrationStatus\x12\x15\n\roverall_score\x18\x01 \x01(\x02\x12\x1b\n\x13sleeping_confidence\x18\x02 \x01(\x02\"V\n\x05\x45rror\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.study_monitor.ipc.Error.Type\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x13\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.ipc.msg_types.monitor_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONITORMSG']._serialized_start=92
  _globals['_MONITORMSG']._serialized_end=277
  _globals['_CONCENTRATIONSTATUS']._serialized_start=279
  _globals['_CONCENTRATIONSTATUS']._serialized_end=352
  _globals['_ERROR']._serialized_start=354
  _globals['_ERROR']._serialized_end=440
  _globals['_ERROR_TYPE']._serialized_start=421
  _globals['_ERROR_TYPE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
